version: "3"

services:

  db:
    image: postgres:16
    ports: [ "${DBPORT:-5432}:5432" ]
    environment:
      POSTGRES_USER: ${DBUSER:-postgres}
      POSTGRES_PASSWORD: ${DBPASS:-2670467}
      POSTGRES_DB: ${DBNAME:-my_db}
    restart: "always"
